services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  order-service:
    build:
      context: . # project root
      dockerfile: order/Dockerfile # Specify the Dockerfile in the 'order' directory
    depends_on:
      - kafka
    ports:
      - 9080:8080 # Map external port 9080 to internal port 8080
    environment:
      KAFKA_BROKER: kafka:9092 # Internal Kafka communication
      KAFKA_TOPIC: order-received

  inventory-service:
    build:
      context: . # project root
      dockerfile: inventory/Dockerfile # Specify the Dockerfile in the 'order' directory
    depends_on:
      - kafka
    ports:
      - 9081:8080 # Map external port 9080 to internal port 8080
    environment:
      KAFKA_BROKER: kafka:9092 # Internal Kafka communication
      KAFKA_ORDER_RECEIVED: order-received
      KAFKA_ORDER_CONFIRMED: order-confirmed
      KAFKA_ERROR: order-error
