global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "order-error-consumer"
    static_configs:
      - targets: ["metrics-error-consumer:8080"]
  - job_name: "order-time-to-ship-consumer"
    static_configs:
      - targets: ["order-time:8080"]
